### ISSUE TITLE
CRLF line endings in npm release

### ISSUE THREAD

**Issue by davecardwell** [kristiandupont/schemalint#15]
If I download the source bundle from https://github.com/kristiandupont/schemalint/releases/tag/v0.4.2 and extract it the files all have single newline line endings.

However, if I download the published v0.4.2 with `npm i schemalint` the files all have DOS-style CRLF line endings.

This causes problems with `bin/schemalint` on Alpine Linux because of the carriage-return in the opening `#!` line.

```sh
~/app $ file ../node_modules/schemalint/bin/schemalint
../node_modules/schemalint/bin/schemalint: a /usr/bin/env node script, ASCII text executable, with CRLF line terminators

~/app $ ../node_modules/schemalint/bin/schemalint  -v
': No such file or directory
```

Removing the carriage return characters works as expected:

```sh
~/app $ file ../node_modules/schemalint/bin/schemalint
../node_modules/schemalint/bin/schemalint: a /usr/bin/env node script, ASCII text executable

~/app $ ../node_modules/schemalint/bin/schemalint  -v
0.4.2
```

**Comment by kristiandupont** [comment]
Thank you for reporting this. I work both on MacOS and Windows and I must have git configured wrongly somewhere! I'll fix this.

**Comment by kristiandupont** [comment]
Should be fixed now. Let me know if you have other issues.
