### ISSUE TITLE
Chalk v5 being a pure esm package have broken this package pretty much

### ISSUE THREAD

**Issue by zimme** [kristiandupont/schemalint#178]
Hey,

I'm getting `ERR_REQUIRE_ESM` errors using schemalint since 0.5.7 becuase of it using chalk v5 which is a pure esm package and this package isn't I'm guessing.

**Comment by kristiandupont** [comment]
Sorry about that, I fixed the issue in Kanel but obviously it was a problem in this package as well. It should be fixed now.

**Comment by zimme** [comment]
No problem at all. It's hard maintaining OSS and one can't expect anyone to catch all the bugs 😄
