### ISSUE TITLE
Primary Key Rules Fail

### ISSUE THREAD

**Issue by paulgelardi** [kristiandupont/schemalint#251]
The latest version of extract-pg-schema uses the field IsPrimaryKey, but this repo uses the fieldname IsPrimary.  This results in any rules dealing with Primary Keys not behaving as desired.

This affects 1 out-of-the-box rule, which will always fail, as well as the example rule, which will never fail, because of this.

**Comment by kristiandupont** [comment]
Thank you, this should now be fixed!
