### ISSUE TITLE
Hard-coded `schema` on two lines for suggested migration in preferIdentity type rule

### ISSUE THREAD

**Issue by eebbesen** [kristiandupont/schemalint#323]
Text `schema` is prepended to the `DROP SEQUENCE` and `setval` suggestions instead of using `${schemaObject.name}` to get the actual schema. The actual schema is used for the `ALTER TABLE` suggestions.

Here is the output:

```sql
ALTER TABLE "public"."days" ALTER "id" DROP DEFAULT;
DROP SEQUENCE "schema"."days_id_seq";
ALTER TABLE "public"."days" ALTER "id" ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval('"days_id_seq"', max("id")) FROM "schema"."days";
```

https://github.com/kristiandupont/schemalint/blob/d004c63eb3a6269fb0f5805c537ec81d6ee19be5/src/rules/types.ts#L106
https://github.com/kristiandupont/schemalint/blob/d004c63eb3a6269fb0f5805c537ec81d6ee19be5/src/rules/types.ts#L108

I'd be happy to submit a PR for a fix if this is indeed an issue.

**Comment by kristiandupont** [comment]
Okay, that certainly looks like a bug! I'd be happy to merge your PR if you make one!

**Comment by kristiandupont** [comment]
This is now published. Thank you so much for contributing, @eebbesen!

**Comment by eebbesen** [comment]
My pleasure, thank you for creating this, @kristiandupont. Godt nytår!
