### ISSUE TITLE
Linting against an empty schema causes confusing error

### ISSUE THREAD

**Issue by orangain** [kristiandupont/schemalint#329]
### Details
When running schemalint against an empty schema, the following error `TypeError: Cannot read properties of undefined (reading 'tables')` occurs. I think this error is confusing for the first time user of the tool.

```
% npx schemalint
schema-lint
Connecting to postgres on localhost
TypeError: Cannot read properties of undefined (reading 'tables')
    at Object.process (/Users/orange/.npm/_npx/cede960380131524/node_modules/schemalint/build/rules/nameCasing.js:37:22)
    at processDatabase (/Users/orange/.npm/_npx/cede960380131524/node_modules/schemalint/build/engine.js:96:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (/Users/orange/.npm/_npx/cede960380131524/node_modules/schemalint/build/cli.js:60:26)
```

The configuration is as follows.

```js
module.exports = {
  connection: {
    host: "localhost",
    user: "postgres",
    password: "postgres",
    database: "postgres",
    charset: "utf8",
  },

  rules: {
    "name-casing": ["error", "snake"],
    "name-inflection": ["error", "singular"],
    "prefer-jsonb-to-json": ["error"],
    "prefer-text-to-varchar": ["error"],
  },

  schemas: [{ name: "public" }],
};
```

At this time, the `public` schema does exist, but there is no table in it.

```
postgres=# \dn
      List of schemas
  Name  |       Owner
--------+-------------------
 public | pg_database_owner
(1 row)

postgres=# SELECT current_schema();
 current_schema
----------------
 public
(1 row)

postgres=# \dt
Did not find any relations.
```

### Expected behavior:

The `schemalint` command should not cause an error when executed against an empty schema. It would be better to exit successfully because no tables violate the rules. Another option is to display an warning message like "No tables found in the schema" instead of an error.

### Version:

```
% npx schemalint --version
1.0.7
```

----

By the way, schemalint is a very powerful tool for maintaining the quality of the database schema. Thank you for creating such a great tool!

<details open>
<summary>Checklist</summary>

- [X] Modify `src/rules/nameCasing.ts` ✓ https://github.com/kristiandupont/schemalint/commit/7815a3efd9d793dce4d21f68dd0a2f8a057625ae [Edit](https://github.com/kristiandupont/schemalint/edit/sweep/linting_against_an_empty_schema_causes_c/src/rules/nameCasing.ts#L56-L63)
- [X] Running GitHub Actions for `src/rules/nameCasing.ts` ✓  [Edit](https://github.com/kristiandupont/schemalint/edit/sweep/linting_against_an_empty_schema_causes_c/src/rules/nameCasing.ts#L56-L63)
- [X] Modify `src/engine.js` ✓ https://github.com/kristiandupont/schemalint/commit/56a4c852b4e6e36425249020aa578e66d27d0c77 [Edit](https://github.com/kristiandupont/schemalint/edit/sweep/linting_against_an_empty_schema_causes_c/src/engine.js#L84-L117)
- [X] Running GitHub Actions for `src/engine.js` ✓  [Edit](https://github.com/kristiandupont/schemalint/edit/sweep/linting_against_an_empty_schema_causes_c/src/engine.js#L84-L117)
</details>

**Comment by kristiandupont** [comment]
@orangain I *think* this fixes your issue? I was actually surprised that Sweep went in and did this but it looks pretty solid :-)

**Comment by orangain** [comment]
@kristiandupont The message is now easy to understand. Thank you!

This is the first time I have seen Sweap and I too was surprised that it created a pull request exactly from the content of the issue. However, I am concerned about the following two points.

1. There are changes made that are not relevant to this issue, but I am not sure if they are correct or not.
2. There were other ways to address this issue, so I am not sure if this was really a good solution. For example, for an empty schema, one could change extract-pg-schema to return a schema object containing an empty array instead of undefined.

**Comment by kristiandupont** [comment]
Yeah, those are good points and it's definitely a flaw in extract-pg-schema that I should get fixed :-)
