### ISSUE TITLE
Proposal: addition of new built-in rules

### ISSUE THREAD

**Issue by orangain** [kristiandupont/schemalint#341]
I would like to propose the addition of new built-in rules. These four rules should not always be used, but would be useful in some cases.

I understand that writing custom rules are encouraged, but I do not think it is always easy to test custom rules. I believe it is helpful that the schemalint provides robust and well-tested built-in rules.

If these rules are worth adding to the built-in rules, I would like to send a pull request to add them. I would be happy to hear your thoughts on these rules. Feedbacks on the rule names and option formats are also welcome.

## 1. `index-referencing-column`

This rule requires that the referencing column (not the referenced column) of a foreign key constraint be indexed.

As the [postgres document](https://www.postgresql.org/docs/16/ddl-constraints.html#DDL-CONSTRAINTS-FK:~:text=Since%20a%20DELETE,the%20referencing%20columns) says, it is not always needed to index the referencing columns, but it is often a good idea to do so.

> Since a DELETE of a row from the referenced table or an UPDATE of a referenced column will require a scan of the referencing table for rows matching the old value, it is often a good idea to index the referencing columns too. Because this is not always needed, and there are many choices available on how to index, the declaration of a foreign key constraint does not automatically create an index on the referencing columns.

Example usage:

```js
  rules: {
    'index-referencing-column': ['error'],
  }
```

Other candidates for the rule name:

- `index-on-referencing-column`
- `require-index-on-referencing-column`

## 2. `reference-actions`

This rule requires that a foreign key reference have specific `ON UPDATE` and `ON DELETE` actions.

The `ON UPDATE` and `ON DELETE` actions are important for maintaining data integrity. Some projects may have specific requirements for these actions. For example, it may be required that the `ON DELETE` action is `NO ACTION` to prevent accidental deletion of data. Another example is that it may be required that the `ON UPDATE` action is `CASCADE` to keep the data consistent.

Example usage:

```js
  rules: {
    'reference-actions': ['error', {
      onUpdate: 'NO ACTION',
      onDelete: 'CASCADE',
    }],
  }
```

When one of the `onUpdate` or `onDelete` is not specified, the rule allows any action for the unspecified one.

Other candidates for the rule name:

-  `require-reference-actions`

## 3. `row-level-security`

This rule requires that row-level security (RLS) is enabled on a table. Optionally, it can require that RLS is enforced.

RLS is a feature that allows for restricting rows returned by normal queries or data modification operations. It is useful for multi-tenant applications and other cases where data isolation is required. If a user forgets to enable RLS, it can cause a security issue. Of course, it is not always needed to enable RLS, but this rule can be useful for projects that require RLS.

Example usage:
    
```js
rules: {
    'row-level-security': ['error'], // RLS must be enabled on all tables
}
```

```js
rules: {
    'row-level-security': ['error', {enforced: true}], // RLS must be enabled and enforced on all tables
}
```

When the option is not specified or `enforced` is `false`, the rule only requires that RLS is enabled. When `enforced` is `true`, the rule requires that RLS is enabled and enforced.

Other candidates for the rule name:

- `enable-row-level-security`
- `enable-rls`
- `require-row-level-security`
- `require-rls`

## 4. `mandatory-columns`

This rule requires that a table has certain columns.

Some projects have columns that are required for the table. For example, a `created_at` column is often mandatory for a table to record when the row was created. Another example is that a `tenant_id` column is often mandatory for a multi-tenant application.

Example usage:

```js
rules: {
    'mandatory-columns': ['error', {
        tenant_id: {
            expandedType: 'pg_catalog.int4',
            isNullable: false,
            ordinalPosition: 1,
        },
        created_at: {
            expandedType: 'pg_catalog.timestamptz',
            isNullable: false,
        }
    }
}
```

Option of the rule is an object, where the key is the column name and the value is an object that is a required subset of the `TableColumn` type. The `ordinalPosition` can be used to ensure that the column is in the expected position.

My concern is that `expandedType` is not always easy to obtain; instead of giving up the flexibility to specify any property of a `TableColumn`, it might be better to allow a simple specification, such as `type: "int"`.

Other candidates for the rule name:

- `require-columns`
- `fixed-columns`

**Comment by kristiandupont** [comment]
I like all of these. I personally have rules that match tables with certain tags.I wonder if that is something worth exploring here -- i.e. if a table has a comment that includes the tag `@record_delete`, it should have [archiving triggers](https://brandur.org/fragments/deleted-record-insert).

**Comment by orangain** [comment]
@kristiandupont Thanks for the response. Do you mean that the rules should be able to apply to only some tables, rather than all tables? I think it is true that some rules are desirable to apply only to some tables, and it would be nice if schemalint could provide a way to do so.

However, I am concerned that if a rule is applied only to tables with a specific tag, it may be difficult for a developer to notice when they forget to tag a table. I think it would be better to apply the rule to all tables by default, and then specify the tables to exclude with `ignores`.

Nevertheless, if there are more tables to exclude, I understand that it is more convenient to be able to choose which tables to apply the rule to. It might also be useful to be able to specify different options for different tables in the same rule. One table could have this option, another table could have another option, and so on.

**Comment by kristiandupont** [comment]
I guess what I am getting at is that maybe there should be a general way to apply rules to certain items. Whether whitelists or blacklists or some other measure. But that doesn't actually conflict with what you are suggesting here, so there is no need to dig into that any further in this thread. :-)

**Comment by orangain** [comment]
All proposed rules have been merged.
