### ISSUE TITLE
Issue with irregular-plurals library when attempting to use schemalint library 2.0.1

### ISSUE THREAD

**Issue by dblake-motor** [kristiandupont/schemalint#370]
### Details
It appears that there is an issue with the update to the latest version of the irregular-plurals library.

We were attempting to use the latest version of the schemalint library (2.0.1) and received an error message: 
```
/usr/lib/node_modules/schemalint/build/rules/nameInflection.js:30
const irregular_plurals_1 = __importDefault(require("irregular-plurals"));

Error [ERR_REQUIRE_ESM]: require() of ES Module /usr/lib/node_modules/schemalint/node_modules/irregular-plurals/index.js from /usr/lib/node_modules/schemalint/build/rules/nameInflection.js not supported.
Instead change the require of index.js in /usr/lib/node_modules/schemalint/build/rules/nameInflection.js to a dynamic import() which is available in all CommonJS modules.
at Object.<anonymous> (/usr/lib/node_modules/schemalint/build/rules/nameInflection.js:30:45) {
code: 'ERR_REQUIRE_ESM'
```

I ran my container again using version 2.0.0 and everything ran normally.

**Comment by kristiandupont** [comment]
Sorry, for some reason I missed this issue! I published a new version that rolls the package back for now. I need to update Schemalint to work with ESM

**Comment by dblake-motor** [comment]
Thank you, everything is working as normal.
