### ISSUE TITLE
Question about new rules??

### ISSUE THREAD

**Issue by zendern** [kristiandupont/schemalint#6]
So we have have 2 custom rules we plan to build as of right now and of course we can use those as they are via the functionality of `plugins` so that is great. 

But i was wondering at what point if any would you like rules to be added to the main project?? 
What criteria is there that would make it main project worthy?? 
Or maybe the this issue shifts more into how do we do something for plugins that is not just directory based (since the lookup has a `cwd()` in it but instead npm package, github url, etc.

Currently we are working on building the following rules: 

1. **prefer timestampz over timestamp** - we would like to be explicit once time is involved so thus forcing a timezone
2. **column naming consistency** - diffing across the tables to make sure columns are in fact named in similar ways. Example if you have a column named `center_id` in one table and in another table you have `centerid` this rule would blow up. Both are technically valid with the rules we use today but we are trying to drive consistency so that we always have it one way or another. In this case the suggested alter statement is probably nothing and the error just tells you the tables in questions and makes you pick a direction. (Maybe more can be built here but this is current thought)

**Comment by kristiandupont** [comment]
I tried to keep aligned with ESLint to the extent possible, but there are a number of differences, some obvious and some subtle so we will have to figure it out along the way. I think both of those rules sound general-purpose enough that they would fit in here, so feel free to create a PR.

**Comment by zendern** [comment]
re: aligned with ESLint. That makes sense. 

We will work on getting some PRs together as we work through building out these rules.
